### ISSUE TITLE
[Workshop] MacOS Desktop Wechat Chat Data Export

### ISSUE THREAD

**Issue by xuyuji9000** [xuyuji9000/wechat-playground#2]
- Target machine: macOS
- Target software: Wechat

I'm preparing  a chat data export workshop.

It aims to go through the simplest process of exporting chat data into user friendly format(like sqlite, json, etc).

# Discussion Notes from [xinchejian](https://github.com/xinchejian/)  Collaborators

- Question: 那么如果要做一次这样的工作坊应该用什么样的形式呢？ 

      K: 我能够想到的是
      - 需要列出参与者的约束条件
        比如机器类型，配置，etc
      - 提前准备好更加初学者友好的教程，讲解涉及到的概念
    
      A: 如果你做wechat hacking，那就得考虑用户用的不是mac的情况.  
      如果你做mac hacking，那么可能需要增加些别的内容
    
      K: 应该是wechat hacking
      如果要做到对各种常用操作系统inclusive 的话
      那就还需要看一下
      是不是应该准备一下Linux客户端和Windows客户端的玩法
    
      J: 首先确定整个流程是多久可以完成的 
      假设工具包让参与者提前预装好 
      这个微信信息从抓包处理到到解析完成的数据是需要一小时还是两小时 还是要更久的时间
    
      然后不太需要考虑全平台的事情 win和linux的也可以参加 日后再交流就好 又不是培训机构
    
      工具包就你提供就好 打个zip让参加者自己来工作坊之前装上
    
      K: 可以预装的工具
      应该也是主要通过文档的方式，列出操作流程
      让准备参与的人自己按照步骤安装
      不会的，在工作坊的现场，辅助安装
    
      J: 就假设这是一个两小时的workshop 
      那前20分钟就肯定是一个简单的ppt 讲解今天整个流程 要用多久 用什么工具 怎样处理 然后就是处理好的数据能做什么用途
      然后就进入手把手教学阶段

- Question: 是不是可以用AWS MacOS spot instance 来作为标准的分享机器?

      A: 另一个选择：使用AWS服务器的话，可以统一环境。
    
      如果使用spot instance, 几个小时的成本应该不高
    
      成功运行一个M1的instance，需要额外配置dedicated host，比较麻烦。另外没有spot instance可用，必须付全价
    
      intel cpu大约1美元/小时，M1 cpu大约0.65美元/小时
    
      其实就是租用一个云端的mac mini
    
      AWS的mac服务器有个坑，dedicated host起步必须24小时以上。所以最低测试成本约0.65x24 = 15.6美元，用完还得记得删除dedicated host

# Action Points

- [x] 准备机器类型限制

- [ ] 准备软件预装步骤文档
  - 需要梯子的预装方式
  - 不需要梯子的预装方式

- [ ] 预估workshop的时长，包括开始的PPT介绍和后续的实操

- [ ] 准备workshop PPT
  - 介绍workshop预计时长
  - 用到哪些工具
  - 怎么处理
  - 数据导出有什么用途
  - 为什么探索Wechat数据导出
  - 我是怎么鼓捣明白的
  
# Output

-  [workshop-extract-macos-desktop-wechat-chat-data](https://github.com/xuyuji9000/wechat-playground/blob/master/workshop-extract-macos-desktop-wechat-chat-data/Readme.md)

# Reference

- [超简单：mac导出微信聊天记录（附上粉丝群全部聊天记录）](https://zhuanlan.zhihu.com/p/409662291)
- [Compound pejoratives on Reddit – from buttface to wankpuffin](https://colinmorris.github.io/blog/compound-curse-words)

**Comment by lcb931023** [comment]
之前参加过一个MITM工作坊，虽然大家都是mac系统，软件预装那一步还是很麻烦，因为大部分来的人都没有 :ladder: 导致一些包下载出错。

**Comment by xuyuji9000** [comment]
> 之前参加过一个MITM工作坊，虽然大家都是mac系统，软件预装那一步还是很麻烦，因为大部分来的人都没有 🪜 导致一些包下载出错。

嗯...

没有梯子。
这个就很麻烦。

@lcb931023 

我现在理解的话，面对这个问题有两个应对方式
- 在workshop的过程中，让没有梯子的用户也开始尝试
  如果无法成功，那么没有梯子的人就不是目标用户

- 还有一种方式是，预先准备软件的文档，分两种：
  - 一种是给有梯子的用户的，这个简单
  - 一种是给没有梯子的用户的，这个就需要workshop的准备者花精力准备出，不用梯子的安装方式

**Comment by lcb931023** [comment]
还有一个办法，就是公用 🪜  😉 

这个线下更方便

**Comment by xuyuji9000** [comment]
emmm @lcb931023 

如果线下一起安装的话，准备时间应该会很长

比如我之前安装xcode, 100MB的宽带， 从下载到安装结束，一共花了2-3h。

就感觉这个安装的步骤应该尽量让参加者提前自己搞定。

**Comment by xuyuji9000** [comment]
Auguest 建议了微信聊天记录生成词云的参考资料

# Reference
- [微信聊天记录生成词云](https://zhuanlan.zhihu.com/p/82501634)
- [【Python】用于微信聊天记录的word cloud,制作,词云](https://www.pythonf.cn/read/103017)

**Comment by xuyuji9000** [comment]
新车间opennight 20220713 成果物，[THE W4HW Bible](https://shimo.im/docs/zdkyBaBwBZhlEPA6)
> W4HW stands for (workshop for hosting workshop)

**Comment by xuyuji9000** [comment]
This issue is paused.
